// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylqkqygbinoptzgozxjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscWtxeWdiaW5vcHR6Z296eGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzgxMTAsImV4cCI6MjA3MDg1NDExMH0.bdF17KZUat8DQLXrfuQNQKvXygyIOYL7M5fT8Hy0LXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});